Vagrant.configure(2) do |config|
        config.vm.provider "docker" do |docker, override|
        override.vm.box = nil
        docker.build_dir = "."
        override.ssh.insert_key = true
        docker.has_ssh = true
        docker.privileged = true
    end
	config.vm.provision "file", source: "/Users/bilgem/Development/example-devops-project/hello-world", destination: "/home/vagrant/hello-world"
	config.vm.provision "file", source: "/Users/bilgem/Development/example-devops-project/jenkins", destination: "/home/vagrant/jenkins"

	config.vm.network "forwarded_port", guest: 8080, host: 8085
end
    
