ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'

Vagrant.configure(2) do |config|
  # Define VMs with static private IP addresses, vcpu, memory and vagrant-box.
    boxes = [
        {
            :name => "host1",    
        },
        {
            :name => "host2",
        },
        {
            :name => "host3",
        }
    ]

    # Provision each of the VMs.
    boxes.each do |opts|
        config.vm.define opts[:name] do |config|
            config.vm.hostname = opts[:name]
            config.vm.provider "docker" do |docker, override| #  Defines the vagrant provider
            override.vm.box = nil
            docker.build_dir = "."
            #override.ssh.insert_key = true
            docker.has_ssh = true
            docker.privileged = true
            docker.create_args = ['--cpuset-cpus=1']
            docker.create_args = ['--memory=2g']
            end
        end
    end
end
